# Generated by Django 3.0.8 on 2020-12-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'offre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.DO_NOTHING, to='supermarche.Offre')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
    ]
