# Generated by Django 3.0.8 on 2020-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nomprenom', models.CharField(max_length=250)),
                ('carte_fidelite', models.IntegerField()),
                ('somme', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
