# Generated by Django 3.0.8 on 2020-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='carte_fidelite',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='somme',
            field=models.CharField(max_length=250),
        ),
    ]
