# Generated by Django 3.0.8 on 2020-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0006_clientproduits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinPanier',
            fields=[
                ('id_panier', models.AutoField(primary_key=True, serialize=False)),
                ('quantité', models.IntegerField()),
            ],
            options={
                'db_table': 'min_panier',
                'managed': False,
            },
        ),
    ]
